fix bugs in  truncated_normal; add TruncatedNormal init.
brainpy/BrainPy pull request #575
Opened 2024-01-01 02:34 UTC by charlielam0615

## Description
<!--- Why is this change required? What problem does it solve? -→
1. `random.truncated_normal` is not properly truncated.
2. add support for `TruncatedNormal` initialization

<!--- Describe your changes in detail here to communicate to the maintainers why this pull request should be accepted -→
<!--- Describe your technology stack here if not a documentation update -→
<!--- Tasklist format is recommended for all pull requests and is required for all draft pull requests. You can couple your description with the tasklist -→
<!--- If it fixes an open issue, please link to the issue here in the last line. -→
bug fix is a re-implementation of PR#574, also fix bugs therein.

## How Has This Been Tested
<!--- Please describe in detail how you tested your changes locally -→
Passed local test.
<!--- Include details of your testing environment, and the tests you ran to -→
<!--- For example, markdown files should pass markdownlint locally according to the rules -→
<!--- See how your change affects other areas of the code, etc. -→

## Types of changes
<!--- What types of changes does your code introduce? -→
<!--- Only left the line that best describes this pull request -→
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Checklist
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -→
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -→
- [x] Code follows the code style of this project.
- [x] Changes follow the **CONTRIBUTING** guidelines.
- [x] Update necessary documentation accordingly.
- [x] Lint and tests pass locally with the changes.
- [x] Check issues and pull requests first. You don't want to duplicate effort.

## Other information

2024-01-01 03:42 UTC, chaoming0625 requested changes
I think we should first merge #574, then merge the latest changes, and finnally the ``brainpy.init.TruncatedNormal`` should work. 

Moreover, please add the new APIs into the ``bainpy.intialize`` module and corresponding doc in ``docs\apis\initialize.rst``

2024-01-01 03:42 UTC, chaoming0625 commented on brainpy/_src/math/random.py
> +  def truncated_normal(self, lower, upper, size=None, scale=1, loc=0, key=None):
``truncated_normal`` sampling has been revised. Please see #574

2024-01-01 03:42 UTC, chaoming0625 commented on brainpy/_src/initialize/random_inits.py
> +class TruncatedNormal(_InterLayerInitializer):
Great!

2024-01-02 05:16 UTC, charlielam0615 commented
@chaoming0625 
PR #574 merged.
New API added.

2024-01-02 05:50 UTC, chaoming0625 approved these changes
So great PR!

2024-01-02 05:50 UTC, merged