[dnn] Add dnn.linear taichi implmentation
brainpy/BrainPy pull request #598
Opened 2024-01-22 09:25 UTC by Routhleck

Add dnn.linear taichi implmentation

2024-01-25 09:35 UTC, Routhleck reviewed
Ready to pull request

2024-01-26 03:29 UTC, chaoming0625 commented on brainpy/_src/dnn/linear.py
> +import taichi as ti
Do not use this kind of import internally.

2024-01-26 03:31 UTC, chaoming0625 requested changes
I am confused by the code in this PR. The discussion may be needed.

2024-01-28 14:30 UTC, Routhleck commented
Replace with taichi op 

* [x] event csr matvec:
  cpu default: taichi
  gpu default: brainpylib(cusparse)
* [x] csr matvec
  cpu default: taichi
  gpu default: taichi
* [x] jitconn event matvec
  cpu default: taichi
  gpu default: taichi(outdim parallel=False) brainpylib(outdim parallel=True)
* [x] jitconn matvec
  cpu default: taichi
  gpu default: taichi(outdim parallel=False) brainpylib(outdim parallel=True)

2024-01-29 05:07 UTC, Routhleck commented
Set all operators to using taichi kernel defaultly

2024-01-29 15:14 UTC, chaoming0625 approved these changes
Great!

2024-01-29 15:15 UTC, merged